
[fearfire]
	#A list of entity IDs (e.g. 'minecraft:pig') that will have the Fear AI.
	#Only these entities will run away from blocks/items set below.
	entities = ["fossil:brachiosaurus", "fossil:gallimimus", "fossil:parasaurolophus", "fossil:dryosaurus", "fossil:pachyrhinosaurus", "fossil:quagga", "fossil:triceratops", "fossil:pachycephalosaurus", "fossil:psittacosaurus", "fossil:protoceratops", "fossil:dodo", "fossil:ankylosaurus", "fossil:stegosaurus", "fossil:mammoth", "fossil:megaloceros", "fossil:elasmotherium", "fossil:platybelodon"]
	#Any block in this list will scare the entity if found within the search radius.
	blocks = ["minecraft:fire", "minecraft:campfire", "minecraft:glowstone"]
	#Any item in this list will scare the entity if a nearby player is holding it (main or off hand).
	items = ["minecraft:torch", "minecraft:glowstone"]

	[fearfire.optimizations]
		#If true, skip block checks if the gamerule 'doFireTick' is off.
		skipBlockCheckIfFireTickOff = true
		#Number of ticks between scanning for threats. 20 = 1 second.
		scanCooldownTicks = 120
		#Horizontal radius to find players holding feared items.
		playerCheckRadius = 8
		#Vertical (Y) range to check for item-holding players.
		playerCheckVerticalRange = 2
		#Only check for fear blocks if there's at least one player within this radius (X,Z ±, Y ±2). If no player is near, we skip block checks to save CPU.
		blockCheckPlayerRadius = 32

